name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install modified stdlib
      run: git clone https://github.com/sugarfi/crystal.git cr && export CRYSTAL_PATH="$(pwd)/cr:$(pwd)/lib"
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
